import Head from "next/head";
import Navbar from "@/components/navbar/Navbar";
import HomeSection from "@/components/sections/principal_website/Home";
import ServicosSection from "@/components/sections/principal_website/Servicos";
import MotivosSection from "@/components/sections/principal_website/Motivos";
import IntegrantesSection from "@/components/sections/principal_website/Integrantes";
import FAQSection from "@/components/sections/principal_website/FAQ";
import DuvidasSection from "@/components/sections/principal_website/Duvidas";

const Home = () => {
  return (
    <>
      <Head>
        <title>CativaWeb</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <>
          <Navbar />
          <div style={{ margin: "80px" }}>
            <HomeSection />
            <ServicosSection />
            <MotivosSection />
            <IntegrantesSection/>
            <FAQSection/>
            <DuvidasSection/>
            <br/>
            <br/>
            <br/>
          </div>
        </>
      </main>
    </>
  );
};

export default Home;
