import Head from "next/head";
import Navbar from "@/components/navbar/Navbar";
import HomeSection from "@/components/sections/principal_website/Home";
import ServicosSection from "@/components/sections/principal_website/Servicos";
import MotivosSection from "@/components/sections/principal_website/Motivos";
import IntegrantesSection from "@/components/sections/principal_website/Integrantes";
import FAQSection from "@/components/sections/principal_website/FAQ";
import DuvidasSection from "@/components/sections/principal_website/Duvidas";
import RodapeSection from "@/components/sections/principal_website/Rodape";
import { useSizeScreen } from "./hooks/useSizeScreen";

const Home = () => {

  const {width, height} = useSizeScreen()

  return (
    <>
      <Head>
        <title>CativaWeb</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <>
          <Navbar />
          {width}x{height}
          <div style={{ margin: "80px 80px 30px 80px" }}>
            <HomeSection />
          </div>
          <ServicosSection />
          <MotivosSection />
          <div style={{ margin: "80px 80px 30px 80px" }}>
            <IntegrantesSection />
            <FAQSection />
            <DuvidasSection />
          </div>
          <RodapeSection />
        </>
      </main>
    </>
  );
};

export default Home;
